backend:
  name: github
  repo: xaverpollinger/xaverfriedrich
  branch: main

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:

  - name: "projekte"
    label: "Projekte"
    folder: "src/projekte"
    create: true
    slug: "{{slug}}"
    filter:
      field: layout
      value: projekt.njk
    fields:
      - { label: "Layout",       name: "layout",      widget: "hidden", default: "projekt.njk" }
      - { label: "Titel",        name: "title",        widget: "string" }
      - { label: "Beschreibung", name: "description",  widget: "string" }
      - { label: "Jahr",         name: "year",         widget: "number" }
      - { label: "Kunde",        name: "client",       widget: "string", required: false }
      - { label: "Rolle",        name: "role",         widget: "string", required: false }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - label: "Cover-Bild"
        name: "cover"
        widget: "image"
        required: false
      - { label: "Inhalt",       name: "body",         widget: "markdown" }
